resources:
  - ccs.yaml
  - cognos-analytics.yaml
  - db2aaservice.yaml
  - db2u.yaml
  - openpages.yaml
  - opensearch.yaml
  - planning-analytics-cluster.yaml
  - planning-analytics.yaml
  - rabbitmq.yaml
