---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    intent: projected
    app.kubernetes.io/instance: ibm-planning-analytics-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ibm-planning-analytics-operator
    control-plane: controller-manager
    icpdsupport/addOn: pa
    icpdsupport/addOnId: pa
    icpdsupport/app: pa
    icpdsupport/module: operators
    component-id: {{ .Chart.Name }}
  name: ibm-planning-analytics-operator
  namespace: {{ .Values.global.operatorNS }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ibm-planning-analytics-operator
  strategy: {}
  template:
    metadata:
      labels:
        intent: projected
        app.kubernetes.io/instance: ibm-planning-analytics-operator
        app.kubernetes.io/name: ibm-planning-analytics-operator
        app.kubernetes.io/managed-by: Helm
        control-plane: controller-manager
        icpdsupport/addOn: pa
        icpdsupport/addOnId: pa
        icpdsupport/app: pa
        icpdsupport/module: operators
    spec:
      containers:
      - args: null
        env:
        - name: ANSIBLE_DEBUG_LOGS
          value: "false"
        - name: ANSIBLE_VERBOSITY_PASERVICEINSTANCE_PA_CPD_IBM_COM
          value: "2"
        - name: ANSIBLE_VERBOSITY_PASERVICE_PA_CPD_IBM_COM
          value: "2"
        - name: MAX_CONCURRENT_RECONCILES_PASERVICE_PA_CPD_IBM_COM
          value: "1"
        - name: MAX_CONCURRENT_RECONCILES_PASERVICEINSTANCE_PA_CPD_IBM_COM
          value: "1"
        - name: ANSIBLE_CALLBACK_WHITELIST
          value: profile_roles, profile_tasks
        - name: ANSIBLE_GATHERING
          value: explicit
        - name: BUILD_NUMBER
          value: "{{ .Values.planning_analytics.crVersion }}-1608"
        - name: BETA_CHANNEL
          value: "false"
        {{- $watchNamespaces := .Values.global.tetheredNamespaces | default list -}}
        {{- if .Values.global.instanceNamespace -}}
        {{- $watchNamespaces = append $watchNamespaces .Values.global.instanceNamespace -}}
        {{- end -}}
        {{- $watchNamespaces = prepend $watchNamespaces .Values.global.operatorNamespace }}
        - name: WATCH_NAMESPACE
          value: {{ uniq $watchNamespaces | join "," | quote }}
        - name: OPERATOR_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: DOMAIN_NAME
          valueFrom:
            configMapKeyRef:
              key: domain-name
              name: domain
              optional: true
        {{- if and (eq .Values.global.arch "amd64") (not (empty .Values.planning_analytics.operatorImageDigest.amd64)) }}
        image: '{{ .Values.planning_analytics.devImagePullPrefix | default .Values.global.imagePullPrefix }}/{{ .Values.planning_analytics.operatorImageName }}@{{ .Values.planning_analytics.operatorImageDigest.amd64 }}'
        {{- else if and (eq .Values.global.arch "ppc64le") (not (empty .Values.planning_analytics.operatorImageDigest.ppc64le)) }}
        image: '{{ .Values.planning_analytics.devImagePullPrefix | default .Values.global.imagePullPrefix }}/{{ .Values.planning_analytics.operatorImageName }}@{{ .Values.planning_analytics.operatorImageDigest.ppc64le }}'
        {{- else if and (eq .Values.global.arch "s390x") (not (empty .Values.planning_analytics.operatorImageDigest.s390x)) }}
        image: '{{ .Values.planning_analytics.devImagePullPrefix | default .Values.global.imagePullPrefix }}/{{ .Values.planning_analytics.operatorImageName }}@{{ .Values.planning_analytics.operatorImageDigest.s390x }}'
        {{- end }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 6789
          initialDelaySeconds: 15
          periodSeconds: 20
        name: pa-manager
        readinessProbe:
          httpGet:
            path: /readyz
            port: 6789
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 1500m
            memory: 1Gi
          requests:
            cpu: 50m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
      serviceAccount: {{ .Values.planning_analytics.serviceAccountName }}
      serviceAccountName: {{ .Values.planning_analytics.serviceAccountName }}
      {{- if .Values.global.imagePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.global.imagePullSecret }}
      {{- end }}
      terminationGracePeriodSeconds: 10
---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    intent: projected
    app.kubernetes.io/instance: ibm-planning-analytics-tm1-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ibm-planning-analytics-tm1-operator
    control-plane: controller-manager
    icpdsupport/addOn: pa
    icpdsupport/addOnId: pa
    icpdsupport/app: pa
    icpdsupport/module: operators
    component-id: {{ .Chart.Name }}
  name: ibm-planning-analytics-tm1-operator
  namespace: {{ .Values.global.operatorNS }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ibm-planning-analytics-tm1-operator
  strategy: {}
  template:
    metadata:
      labels:
        intent: projected
        app.kubernetes.io/instance: ibm-planning-analytics-tm1-operator
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: ibm-planning-analytics-tm1-operator
        control-plane: controller-manager
        icpdsupport/addOnId: pa
        icpdsupport/app: pa
        icpdsupport/module: operators
    spec:
      containers:
      - args: null
        env:
        - name: ANSIBLE_DEBUG_LOGS
          value: "false"
        - name: ANSIBLE_VERBOSITY_TM1_TM1S_IBM_COM
          value: "2"
        - name: ANSIBLE_CALLBACK_WHITELIST
          value: profile_roles, profile_tasks
        - name: ANSIBLE_GATHERING
          value: explicit
        - name: BUILD_NUMBER
          value: 12.4.10_1746122024-559
        - name: BETA_CHANNEL
          value: "false"
        {{- $watchNamespaces := .Values.global.tetheredNamespaces | default list -}}
        {{- if .Values.global.instanceNamespace -}}
        {{- $watchNamespaces = append $watchNamespaces .Values.global.instanceNamespace -}}
        {{- end -}}
        {{- $watchNamespaces = prepend $watchNamespaces .Values.global.operatorNamespace }}
        - name: WATCH_NAMESPACE
          value: {{ uniq $watchNamespaces | join "," | quote }}
        - name: OPERATOR_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: DOMAIN_NAME
          valueFrom:
            configMapKeyRef:
              key: domain-name
              name: domain
              optional: true
        - name: CP4D_RELEASE_VERSION
          value: {{ .Values.planning_analytics.crVersion }}
        {{- if and (eq .Values.global.arch "amd64") (not (empty .Values.planning_analytics.tm1.operatorImageDigest.amd64)) }}
        image: '{{ .Values.planning_analytics.devImagePullPrefix | default .Values.global.imagePullPrefix }}/{{ .Values.planning_analytics.tm1.operatorImageName }}@{{ .Values.planning_analytics.tm1.operatorImageDigest.amd64 }}'
        {{- else if and (eq .Values.global.arch "ppc64le") (not (empty .Values.planning_analytics.tm1.operatorImageDigest.ppc64le)) }}
        image: '{{ .Values.planning_analytics.devImagePullPrefix | default .Values.global.imagePullPrefix }}/{{ .Values.planning_analytics.tm1.operatorImageName }}@{{ .Values.planning_analytics.tm1.operatorImageDigest.ppc64le }}'
        {{- else if and (eq .Values.global.arch "s390x") (not (empty .Values.planning_analytics.tm1.operatorImageDigest.s390x)) }}
        image: '{{ .Values.planning_analytics.devImagePullPrefix | default .Values.global.imagePullPrefix }}/{{ .Values.planning_analytics.tm1.operatorImageName }}@{{ .Values.planning_analytics.tm1.operatorImageDigest.s390x }}'
        {{- end }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 6789
          initialDelaySeconds: 15
          periodSeconds: 20
        name: tm1-manager
        readinessProbe:
          httpGet:
            path: /readyz
            port: 6789
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
      serviceAccount: {{ .Values.planning_analytics.serviceAccountName }} 
      serviceAccountName: {{ .Values.planning_analytics.serviceAccountName }} 
      {{- if .Values.global.imagePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.global.imagePullSecret }}
      {{- end }}
      terminationGracePeriodSeconds: 10
---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    intent: projected
    app.kubernetes.io/instance: ibm-planning-analytics-pass-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ibm-planning-analytics-pass-operator
    control-plane: controller-manager
    icpdsupport/addOn: pa
    icpdsupport/addOnId: pa
    icpdsupport/app: pa
    icpdsupport/module: operators
    component-id: {{ .Chart.Name }}
  name: ibm-planning-analytics-pass-operator
  namespace: {{ .Values.global.operatorNS }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ibm-planning-analytics-pass-operator
  strategy: {}
  template:
    metadata:
      labels:
        intent: projected
        app.kubernetes.io/instance: ibm-planning-analytics-pass-operator
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: ibm-planning-analytics-pass-operator
        control-plane: controller-manager
        icpdsupport/addOn: pa
        icpdsupport/addOnId: pa
        icpdsupport/app: pa
        icpdsupport/module: operators
    spec:
      containers:
      - args: null
        env:
        - name: ANSIBLE_DEBUG_LOGS
          value: "false"
        - name: ANSIBLE_VERBOSITY_PASSSERVICE_PA_CPD_IBM_COM
          value: "2"
        - name: ANSIBLE_GATHERING
          value: explicit
        - name: BUILD_NUMBER
          value: "{{ .Values.planning_analytics.crVersion }}-716" 
        - name: BETA_CHANNEL
          value: "false"
        {{- $watchNamespaces := .Values.global.tetheredNamespaces | default list -}}
        {{- if .Values.global.instanceNamespace -}}
        {{- $watchNamespaces = append $watchNamespaces .Values.global.instanceNamespace -}}
        {{- end -}}
        {{- $watchNamespaces = prepend $watchNamespaces .Values.global.operatorNamespace }}
        - name: WATCH_NAMESPACE
          value: {{ uniq $watchNamespaces | join "," | quote }}
        - name: OPERATOR_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: DOMAIN_NAME
          valueFrom:
            configMapKeyRef:
              key: domain-name
              name: domain
              optional: true
        {{- if and (eq .Values.global.arch "amd64") (not (empty .Values.planning_analytics.pass.operatorImageDigest.amd64)) }}
        image: '{{ .Values.planning_analytics.devImagePullPrefix | default .Values.global.imagePullPrefix }}/{{ .Values.planning_analytics.pass.operatorImageName }}@{{ .Values.planning_analytics.pass.operatorImageDigest.amd64 }}'
        {{- else if and (eq .Values.global.arch "ppc64le") (not (empty .Values.planning_analytics.pass.operatorImageDigest.ppc64le)) }}
        image: '{{ .Values.planning_analytics.devImagePullPrefix | default .Values.global.imagePullPrefix }}/{{ .Values.planning_analytics.pass.operatorImageName }}@{{ .Values.planning_analytics.pass.operatorImageDigest.ppc64le }}'
        {{- else if and (eq .Values.global.arch "s390x") (not (empty .Values.planning_analytics.pass.operatorImageDigest.s390x)) }}
        image: '{{ .Values.planning_analytics.devImagePullPrefix | default .Values.global.imagePullPrefix }}/{{ .Values.planning_analytics.pass.operatorImageName }}@{{ .Values.planning_analytics.pass.operatorImageDigest.s390x }}'
        {{- end }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 6789
          initialDelaySeconds: 15
          periodSeconds: 20
        name: pass-manager
        readinessProbe:
          httpGet:
            path: /readyz
            port: 6789
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
      serviceAccount: {{ .Values.planning_analytics.serviceAccountName }}
      serviceAccountName: {{ .Values.planning_analytics.serviceAccountName }}
      {{- if .Values.global.imagePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.global.imagePullSecret }}
      {{- end }}
      terminationGracePeriodSeconds: 10
